// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmbahimsusgrkcdxwush.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptYmFoaW1zdXNncmtjZHh3dXNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTA4NTQsImV4cCI6MjA3MTUyNjg1NH0._AYO0c_HnV4s6AIkXMOMXCX-Y3nn3rGzGRZPzdPdZ80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});